export const BLUFI_SCAN_SLEEP_TIME: number = 15000;

export const FRICTION_NUMBER: number = 0.6;

export const TWO: number = 2;

export const THREE: number = 3;

export const FOUR: number = 4;

export const FIVE: number = 5;

export const EIGHT: number = 8;

export const TEN: number = 10;

export const TWELVE: number = 12;

export const SIXTEEN: number = 16;

export const TWENTY: number = 20;

export const TWENTY_FOUR: number = 24;

export const THIRTY: number = 30;

export const FORTY: number = 40;

export const FIFTY: number = 50;

export const SIXTY: number = 60;

export const NINETY: number = 90;

export const ONE_HUNDRED_AND_SEVENTH: number = 107;

export const TWO_HUNDRED: number = 200;

export const THREE_HUNDRED: number = 300;

export const FOUR_HUNDRED: number = 400;

export const FIVE_HUNDRED: number = 500;

export const ONE_THOUSAND: number = 1000;